### ISSUE TITLE
Media View Text / Buttons inivisible with Breeze Theme

### ISSUE THREAD

**Issue by Sodivad** [futpib/breeze-tdesktop-theme#1]
Breeze 
![image](https://user-images.githubusercontent.com/8886139/46013576-02a50d00-c0cd-11e8-92aa-1e74eadca5b8.png)
Default  Theme
![image](https://user-images.githubusercontent.com/8886139/46013602-1a7c9100-c0cd-11e8-8c5a-08073120e2fb.png)

**Comment by futpib** [comment]
@Sodivad thanks for taking your time to submit this

**Comment by Sodivad** [comment]
Thanks for creating these themes
