### ISSUE TITLE
Links and icons in chats are bright pink

### ISSUE THREAD

**Issue by l0drex** [futpib/breeze-tdesktop-theme#14]
Links and icons have a bright, pink color. This is hard to read and also isn't part of the Breeze theme.
I suggest using abyss blue (`#2980b9`) for links and plasma blue (`#3daee9`) for the icons.

**Comment by futpib** [comment]
Which of the four themes are you describing? Can you provide a screenshot?

**Comment by l0drex** [comment]
Breeze Light: 
![grafik](https://user-images.githubusercontent.com/46622675/129460624-3db6b168-efad-448a-b5e8-b2dee9afd647.png)

**Comment by l0drex** [comment]
Another thing I just saw: The background of the icons _close_, _minimize_ and _maximize_ have a different background than the title bar in the themes _Breeze_ and _High Contrast_. You can see this in the preview.
