### ISSUE TITLE
New folders sidebar

### ISSUE THREAD

**Issue by alxlg** [futpib/breeze-tdesktop-theme#2]
Would you mind to add support for this new sidebar? It activates from Menu > Settings > Folders

![immagine](https://user-images.githubusercontent.com/26327475/77929302-c9dd8980-72a9-11ea-8b6e-a20143971025.png)

EDIT here there is my fix: https://t.me/addtheme/D6KfqCSCIAjTVWLN

![immagine](https://user-images.githubusercontent.com/26327475/77932638-1dea6d00-72ae-11ea-9426-e7e36c86665d.png)

**Comment by futpib** [comment]
How did you fix it? I could not find the right color keys for the sidebar since the update, I thought they just did not implement theme support for it. Can you point me to the right keys?

**Comment by alxlg** [comment]
@futpib yes, filter the list with "sideBar" and you will get all the colors related to the folders sidebar
