### ISSUE TITLE
Sent icons checkmarks

### ISSUE THREAD

**Issue by pztrn** [futpib/breeze-tdesktop-theme#7]
They're green and looking like a garbage.

Could you please fix them, e.g. made them like pinned icon, or be like selected fg when not selected and white when selected?

https://github.com/telegramdesktop/tdesktop/wiki/Theme-Reference grep for "double tick".

**Comment by futpib** [comment]
@pztrn please post a screenshot or at least tell which theme (out of 4 provided) you are using

**Comment by pztrn** [comment]
Yeah, sorry, using Breeze Dark;

![изображение](https://user-images.githubusercontent.com/869402/94666436-eaed6880-0326-11eb-8027-e7c53265725e.png)

Pretty same for chat pane itself.
